#!/usr/bin/env python3
"""Generate the BAM sine table (1024 entries, Q8.8) as a C header.

Floats stay on the host; the V810 never sees them. Angles are binary
(0..1023 = one full turn) so wrapping is a free AND, and cos is a +256
index shift instead of a second table.
"""
import math

N = 1024
SCALE = 256
B = 8  # entries per output line

print("/* generated by tools/gen_sin.py -- do not edit by hand */")
print("#ifndef SIN_TABLE_H")
print("#define SIN_TABLE_H")
print("")
print("/* Q8.8 sine over BAM angle 0..%d (1024 = full turn)." % (N - 1))
print(" * cos(a) = g_sin[(a + 256) & 1023]. */")
print("static const signed short g_sin[%d] = {" % N)
for i in range(0, N, B):
    row = ", ".join(
        str(int(round(math.sin(2.0 * math.pi * (i + j) / N) * SCALE)))
        for j in range(B)
    )
    print("    " + row + ",")
print("};")
print("")
print("#endif")
