#!/usr/bin/env python3
"""gen_pcfx_sky.py — build the PC-FX RAINBOW sky asset from a Doom sky texture.

Decodes the SKY1 patch (256x128) to RGB via PLAYPAL, expands it to a 256x240
image (the RAINBOW plane), encodes it to a HuC6271 RAINBOW YUV/DCT stream with
tools/gen_pcfx_rainbow_bg.py, and emits a C header holding the stream as a
linkable byte array plus the transfer parameters. At runtime the stream is copied
into KRAM page 1 and decoded by the RAINBOW hardware to form the sky, shown behind
the KING framebuffer wherever the renderer leaves transparent (index-0) pixels.

Usage: gen_pcfx_sky.py <wad> <out.h> [--patch SKY1]
"""
import sys, struct, subprocess, re, argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent


def wad_lump(path, name):
    d = open(path, 'rb').read()
    _, n, off = struct.unpack('<4sII', d[:12])
    for i in range(n):
        e = d[off + i * 16:off + i * 16 + 16]
        fp, sz = struct.unpack('<II', e[:8])
        nm = e[8:16].split(b'\0')[0].decode('latin1')
        if nm == name:
            return d[fp:fp + sz]
    return None


def decode_patch(data):
    w, h, lo, to = struct.unpack('<HHhh', data[:8])
    colofs = struct.unpack('<%dI' % w, data[8:8 + 4 * w])
    img = bytearray([0]) * (w * h)
    for x in range(w):
        o = colofs[x]
        while data[o] != 0xff:
            top = data[o]; ln = data[o + 1]
            src = o + 3
            for y in range(ln):
                yy = top + y
                if 0 <= yy < h:
                    img[yy * w + x] = data[src + y]
            o = src + ln + 1
    return w, h, bytes(img)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('wad')
    ap.add_argument('out_h')
    ap.add_argument('--patch', default='SKY1')
    a = ap.parse_args()

    from PIL import Image

    patch = wad_lump(a.wad, a.patch)
    if not patch:
        sys.exit(f'{a.patch} not found in {a.wad}')
    pal = wad_lump(a.wad, 'PLAYPAL')[:768]
    w, h, idx = decode_patch(patch)

    im = Image.frombytes('P', (w, h), idx)
    im.putpalette(pal)
    im = im.convert('RGB')
    # Expand the 256x128 sky to the 256x240 RAINBOW plane: sky on top, the top
    # row extended upward is unnecessary — instead tile the sky down so the lower
    # (below-horizon) area is also filled with sky rather than black.
    sky = Image.new('RGB', (256, 240))
    src = im.resize((256, 128), Image.NEAREST)
    sky.paste(src, (0, 0))
    sky.paste(src, (0, 128))          # tiled continuation for rows 128..239
    tmp_png = HERE.parent / 'generated' / 'sky.png'
    tmp_bin = HERE.parent / 'generated' / 'sky.bin'
    tmp_h = HERE.parent / 'generated' / 'sky_rb.h'
    tmp_png.parent.mkdir(parents=True, exist_ok=True)
    sky.save(tmp_png)

    subprocess.run([sys.executable, str(HERE / 'gen_pcfx_rainbow_bg.py'),
                    '--header', str(tmp_h), str(tmp_png), str(tmp_bin), 'SKY'],
                   check=True)

    stream = open(tmp_bin, 'rb').read()

    # The sky is DMA'd to page-1 word 0 and the ADPCM sample bank starts at
    # SKY_RESERVE_WORD (tools/gen_pcfx_sfx.py). An oversized stream does not
    # fail loudly -- it silently overwrites the first sounds in the bank, which
    # then decode as noise. Stream size moves with the picture and with any
    # change to the quantization tables, so check it here rather than assume.
    sys.path.insert(0, str(HERE))
    from gen_pcfx_sfx import SKY_RESERVE_WORD
    if len(stream) > SKY_RESERVE_WORD * 2:
        sys.exit(f'SKY: stream {len(stream)} bytes exceeds the '
                 f'{SKY_RESERVE_WORD * 2}-byte page-1 reserve; raise '
                 f'SKY_RESERVE_WORD in tools/gen_pcfx_sfx.py')

    defs = open(tmp_h).read()
    start = re.search(r'TRANSFER_START (\d+)u', defs).group(1)
    blocks = re.search(r'BLOCK_COUNT (\d+)u', defs).group(1)

    # The RAINBOW stream is NOT linked into the program — it is embedded on the CD
    # and DMA'd into KRAM at runtime (the HuC6271 only decodes CD-DMA'd KRAM data).
    # Emit the raw stream next to the header for the CD `append`, and a header with
    # just the sizes/params the loader needs.
    import os
    out_bin = os.path.splitext(a.out_h)[0] + '.bin'
    with open(out_bin, 'wb') as f:
        f.write(stream)

    with open(a.out_h, 'w') as f:
        f.write('/* Generated by tools/gen_pcfx_sky.py — do not edit. */\n')
        f.write('#ifndef PCFX_SKY_H\n#define PCFX_SKY_H\n\n')
        f.write(f'#define PCFX_SKY_BYTES {len(stream)}u\n')
        f.write(f'#define PCFX_SKY_TRANSFER_START {start}u\n')
        f.write(f'#define PCFX_SKY_BLOCK_COUNT {blocks}u\n')
        f.write('#endif\n')
    print(f'SKY: stream {len(stream)} bytes -> {out_bin} (CD-embedded) + {a.out_h}')

    print(f'SKY: {a.patch} {w}x{h} -> RAINBOW stream {len(stream)} bytes -> {a.out_h}')


if __name__ == '__main__':
    main()
