#!/usr/bin/env python3
"""Bake the complete fade; the V810 only writes palette words each field."""
from pathlib import Path
import importlib.util

ROOT = Path(__file__).resolve().parents[3]
CONVERTER = ROOT / "PCFX_Skills/pcfx-yuv-palette/rgb_to_yuv.py"
spec = importlib.util.spec_from_file_location("rgb_to_yuv", CONVERTER)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

# Index zero remains the black backdrop; all opaque pixels use 1..15.
COLORS = [(0, 0, 0), (255, 255, 255), (255, 64, 64), (64, 192, 255),
          (255, 208, 48), (80, 224, 112), (200, 96, 240), (128, 128, 128),
          (255, 128, 48), (48, 96, 224), (192, 64, 128), (96, 240, 208),
          (240, 240, 112), (112, 160, 64), (64, 64, 64), (208, 208, 208)]

rows = []
for step in range(32):
    # Integer RGB scale mirrors a conventional fade's rounded channels.
    rows.append([module.rgb_to_yuv(*((c * step + 15) // 31 for c in rgb))
                 for rgb in COLORS])

output = ROOT / "examples/palette-fade/src/fade_palette.h"
with output.open("w") as stream:
    stream.write("/* Generated by tools/make_palette.py; Y8U4V4. */\n")
    stream.write("static const u16 fade_palette[32][16] = {\n")
    for row in rows:
        stream.write("    {" + ", ".join("0x%04x" % value for value in row) + "},\n")
    stream.write("};\n")
