/* RAINBOW (HuC6271) still image with endless horizontal pan.
 *
 * The encoded stream is a cdlink `append` file.  It is DMA'd from the disc
 * straight into KRAM by the KING SCSI engine (eris_cd_read_kram), then the
 * HuC6271 is re-armed once per field to decode it again.  Every step mirrors a
 * measured-working runtime: vendor/doompcfx/platform/i_system_pcfx.c (sky) and
 * pcfx_rainbow_mp2_startup_sync_package (PCFV player).  PCFX_Skills/pcfx-rainbow
 * explains each rule.
 */
#include <pcfx/types.h>
#include <pcfx/v810.h>
#include <pcfx/king.h>
#include <pcfx/tetsu.h>
#include <eris/cd.h>

#include "lbas.h"            /* generated by pcfx-cdlink: asset LBA   */
#include "rainbow_still.h"   /* generated by rainbow.py image: sizes  */

#ifndef BINARY_LBA_BUILD_STILL_BIN
#define BINARY_LBA_BUILD_STILL_BIN 0u
#endif

/* eris_cd_read_kram is hardware-confirmed for one 16 KiB arm at KRAM word
 * 0x08000 (libpcfx eris/cd.h); the Makefile caps the stream at 16 KiB. */
#define RB_KRAM_WORD        0x08000u
#define RB_TRANSFER_START   6u     /* transfer 16 rasters before display  */
#define RB_REARM_FIRST      248u   /* decode of this field is done here   */
#define RB_REARM_LAST       261u   /* last active raster (262-line mode)  */

static inline void out_h(u32 port, u16 v)
{
    __asm__ volatile ("out.h %0,0[%1]" : : "r"(v), "r"(port) : "memory");
}

static inline void out_w(u32 port, u32 v)
{
    __asm__ volatile ("out.w %0,0[%1]" : : "r"(v), "r"(port) : "memory");
}

static inline void out_b(u32 port, u8 v)
{
    __asm__ volatile ("out.b %0,0[%1]" : : "r"(v), "r"(port) : "memory");
}

static void king_reg16(u16 reg, u16 v) { out_h(0x600, reg); out_h(0x604, v); }
static void king_reg32(u16 reg, u32 v) { out_h(0x600, reg); out_w(0x604, v); }

/* HuC6261 latch bug: read the raster counter until two reads agree. */
static unsigned raster_stable(void)
{
    unsigned a, b;
    do {
        a = tetsu_get_raster();
        b = tetsu_get_raster();
    } while (a != b);
    return a;
}

/* Decoder ports 0x200..0x214.  Control 0x204 = 3: bit 0 enables decode,
 * bit 1 selects endless scroll so a pan wraps at 256 instead of going black. */
static void rainbow_setup(void)
{
    out_b(0x200, 0);
    out_b(0x202, 0);
    out_h(0x208, 0xFF80);
    out_h(0x20C, 0);
    out_h(0x210, 0);
    out_h(0x214, 0);
    out_h(0x204, 3);
}

static void rainbow_set_hscroll(unsigned x)
{
    out_b(0x200, (u8)(x & 0xFF));
    out_b(0x202, (u8)((x >> 8) & 1));
}

/* One arm decodes exactly one field.  Six KING select/data pairs: keep them
 * interrupt-atomic, a timer IRQ inside a pair corrupts the access on silicon. */
static void rainbow_rearm(void)
{
    int irq = irq_disable();
    king_reg16(0x40, 0x0000);
    king_reg32(0x41, RB_KRAM_WORD);
    king_reg16(0x42, RB_TRANSFER_START);
    king_reg16(0x43, RAINBOW_ASSET_BLOCKS);
    king_reg16(0x44, 0x0000);
    king_reg16(0x40, 0x0001);
    irq_restore(irq);
}

/* Planes are hidden with the video-mode enable bits, not with priority 0:
 * priority 0 is only the bottom of the stack, and every plane needs a unique
 * priority (HuC6261 manual R08-R09, 2.3.3).  RAINBOW is rearmost here. */
static void show_rainbow(int on)
{
    tetsu_set_priorities(7, 6, 5, 4, 3, 2, 1);
    tetsu_set_video_mode(TETSU_LINES_262, 0, TETSU_DOTCLOCK_5MHz,
                         TETSU_COLORS_256, TETSU_COLORS_16,
                         0, 0, 0, 0, 0, 0, on);
}

int main(void)
{
    unsigned last = 0, hscroll = 0;
    int armed = 0;

    king_init();
    king_set_kram_mode(1);          /* 4-Mbit KRAM before any access */
    tetsu_init();
    king_set_kram_pages(0, 0, 0, 0); /* SCSI DMA and RAINBOW share page 0 */
    king_set_bg_prio(KING_BGPRIO_HIDE, KING_BGPRIO_HIDE, KING_BGPRIO_HIDE, KING_BGPRIO_HIDE, 0);
    king_set_bg_mode(KING_BGMODE_NONE, KING_BGMODE_NONE, KING_BGMODE_NONE, KING_BGMODE_NONE);
    show_rainbow(0);

    /* The decoder only takes KRAM data delivered by the KING SCSI engine;
     * an unfed RAINBOW is garbage on hardware, so stay hidden on failure. */
    if (!BINARY_LBA_BUILD_STILL_BIN ||
        !eris_cd_read_kram(BINARY_LBA_BUILD_STILL_BIN, RB_KRAM_WORD,
                           RAINBOW_ASSET_SECTORS * 2048u))
        for (;;) { }

    rainbow_setup();
    for (;;) {
        unsigned r = raster_stable();
        if (r < last)
            armed = 0;               /* the counter wrapped: a new field */
        last = r;
        if (armed || r < RB_REARM_FIRST || r > RB_REARM_LAST)
            continue;
        rainbow_rearm();
        rainbow_set_hscroll(hscroll++ & 0xFF);
        if (hscroll == 2)
            show_rainbow(1);         /* a field has decoded before showing */
        armed = 1;
    }
}
