/*
 * PC-FX project template — KING BG0 256x240 8bpp bitmap, double buffered.
 *
 * This is a VERIFIED-WORKING starting point. It boots, clears the screen to a
 * colour, draws a moving box, reads the pad, and paces itself on the Tetsu
 * raster. Build it, see it, THEN change it.
 *
 * Drawing model:
 *   BG0 is a 256x240 8bpp bitmap living in KRAM. One KRAM word = TWO pixels.
 *   The LEFT pixel is bits 15:8 (high byte), the RIGHT pixel is bits 7:0.
 *   word address = page_base + y * (256/2) + x / 2
 */

#include <pcfx/types.h>
#include <pcfx/king.h>
#include <pcfx/tetsu.h>
#include <pcfx/contrlr.h>

#define SCR_W        256u
#define SCR_H        240u
#define WORDS_PER_ROW (SCR_W / 2u)              /* 2 pixels per KRAM word */
#define PAGE_WORDS   (WORDS_PER_ROW * SCR_H)    /* 30720 words per buffer  */

/* Two buffers so we never draw into the page being displayed. */
#define PAGE0_BASE   0x00000u
#define PAGE1_BASE   PAGE_WORDS

/* ------------------------------------------------------------------ KRAM ---
 * KRAM is NOT memory mapped. Everything goes through KING's I/O ports:
 *   out.h <regno> -> 0x600      (latch which KING register)
 *   out.h <data>  -> 0x604      (read/write that register)
 *
 * The libpcfx king_kram_* wrappers are intentionally not used in the render
 * loop. king_kram_write() reselects KRAM_DATA for every word, adding a call
 * and a register-latch to every pixel pair. The helpers below select KRAM_AWR
 * once, select KRAM_DATA once, and then use the KING auto-increment for the
 * whole burst. The HOST_TEST fallback keeps the helpers usable in a host
 * harness; target builds use only the inline V810 I/O below.
 */

static inline __attribute__((always_inline)) void kram_set_write_inline(
    u32 addr, int incr)
{
#ifdef HOST_TEST
    king_set_kram_write(addr, incr);
#else
    /* Match libpcfx's KWP encoding: A[17:0], signed increment field [27:18]. */
    u32 command = addr | (((u32)incr & 0x000003ffu) << 18);
    __asm__ volatile (
        "out.h %[reg], 0x600[r0]\n"
        "out.w %[command], 0x604[r0]"
        : : [reg] "r" ((u16)0x000d), [command] "r" (command));
#endif
}

static inline __attribute__((always_inline)) void kram_begin_burst(void)
{
#ifndef HOST_TEST
    /* KRAM_AWR leaves register 0x0d selected; latch KRAM_DATA once. */
    __asm__ volatile (
        "out.h %[reg], 0x600[r0]"
        : : [reg] "r" ((u16)0x000e));
#endif
}

static inline __attribute__((always_inline)) void kram_write_latched(u16 word)
{
#ifdef HOST_TEST
    king_kram_write(word);
#else
    __asm__ volatile ("out.h %[word], 0x604[r0]" : : [word] "r" (word));
#endif
}

/* Write a raw 16-bit KING register. libpcfx has no affine helper, so the
 * rotation-unit registers (0x38..0x3d) are written directly like this. */
static void king_reg16(u16 reg, u16 value)
{
    __asm__ volatile (
        "out.h %[reg], 0x600[r0]\n"
        "out.h %[value], 0x604[r0]\n"
        : : [reg] "r" (reg), [value] "r" (value));
}

static void kram_fill(u32 base, u16 word, u32 count)
{
    kram_set_write_inline(base, 1);
    kram_begin_burst();
    while (count--)
        kram_write_latched(word);
}

/* Solid horizontal run of `w` pixels (w must be even, x must be even). */
static void draw_box(u32 base, unsigned x, unsigned y,
                     unsigned w, unsigned h, u8 colour)
{
    u16 pair = (u16)((colour << 8) | colour);
    unsigned row;

    for (row = 0; row < h; row++) {
        unsigned words = w / 2u;
        /* One address setup per row; every word in the row auto-increments. */
        kram_set_write_inline(base + (y + row) * WORDS_PER_ROW + (x / 2u), 1);
        kram_begin_burst();
        while (words--)
            kram_write_latched(pair);
    }
}

/* -------------------------------------------------------------- palette ---
 * The HuC6261 palette is YUV, packed Y8U4V4:  (Y << 8) | (U << 4) | V.
 * U = V = 8 is neutral (grey/no chroma). Y is brightness 0..255.
 * Entry 0 is the transparent/backdrop colour.                          */
static void set_palette(void)
{
    unsigned i;

    for (i = 0; i < 256; i++)
        tetsu_set_palette((u16)i, 0x0188);   /* black, no chroma */

    /* Values generated by PCFX_Skills/pcfx-yuv-palette/rgb_to_yuv.py.
     * Do NOT hand-guess these: Y8U4V4 is not intuitive, and a plausible-
     * looking constant will render a completely different hue. */
    tetsu_set_palette(1, 0x4088);            /* dark grey  */
    tetsu_set_palette(2, 0xC088);            /* light grey */
    tetsu_set_palette(3, 0x1DF6);            /* blue       */
    tetsu_set_palette(4, 0x9730);            /* green      */
    tetsu_set_palette(5, 0x506F);            /* red        */
}

/* --------------------------------------------------------- frame timing ---
 * The Tetsu raster counter (I/O port 0x300, raster in bits 14:5) has a
 * hardware bug: a single read can latch a transitional value. It MUST be read
 * twice and the two reads must agree. This waits for the start of the next
 * field: first spin until we are on the last raster of this frame, then spin
 * until we are not.                                                     */
/* The canonical Tetsu wait-frame routine, in V810 assembly. Reads port 0x300
 * DIRECTLY, so the raster arrives raw as (line << 5) -- hence the 0x3FE0 mask
 * and 0x20A0 (= 261 << 5) constants. Two reads per sample because of the
 * HuC6261 hardware bug; the values must agree before they are trusted.
 *
 * Phase 1 waits until the raster IS the last line of this frame; phase 2 waits
 * until it is NOT, which returns exactly on the wrap into the next frame --
 * the leading edge of vertical blanking, with the whole interval ahead.
 *
 * Do NOT rewrite this in C against tetsu_get_raster(): that helper already
 * decodes the line (`shr 5; andi 0x1FF`), so masking with 0x3FE0 and comparing
 * to 0x20A0 can never match and the wait spins forever.
 *
 * r10-r13 are caller-saved on this ABI, so they need no preservation. */
static inline void wait_frame(void)
{
    __asm__ volatile (
        "movea 0x20A0, r0, r12\n"   /* last raster of the frame */
        "movea 0x3FE0, r0, r13\n"   /* raster bit mask          */

        "1:\n"                      /* wait until this frame is finished */
        "in.h 0x300[r0], r10\n"
        "in.h 0x300[r0], r11\n"     /* read twice: hardware bug */
        "and r13, r10\n"
        "and r13, r11\n"
        "cmp r10, r11\n"
        "bne 1b\n"
        "cmp r10, r12\n"
        "bne 1b\n"

        "2:\n"                      /* then wait until the next one starts */
        "in.h 0x300[r0], r10\n"
        "in.h 0x300[r0], r11\n"
        "and r13, r10\n"
        "and r13, r11\n"
        "cmp r10, r11\n"
        "bne 2b\n"
        "cmp r10, r12\n"
        "be 2b\n"                   /* still the last raster: keep waiting */
        : : : "r10", "r11", "r12", "r13");
}

/* ------------------------------------------------------------------ main ---*/
int main(void)
{
    u16 microprogram[16];
    unsigned i;
    unsigned front = 0;
    int bx = 32, by = 100, vx = 2;
    int old_bx[2] = { -1, -1 };
    int old_by[2] = { 0, 0 };

    king_init();
    tetsu_init();

    /* All KING engines on KRAM page 0. (scsi, bg, rainbow, adpcm) */
    king_set_kram_pages(0, 0, 0, 0);

    /* BG0 = 256-colour bitmap; BG1..3 off. */
    king_set_bg_mode(KING_BGMODE_256_PAL, 0, 0, 0);
    king_set_bg_size(KING_BG0, KING_BGSIZE_256, KING_BGSIZE_256,
                     KING_BGSIZE_256, KING_BGSIZE_256);
    /* CG addresses are in 1024-word units; both BG0 registers must track. */
    king_set_bat_cg_addr(KING_BG0, 0, PAGE0_BASE >> 10);
    king_set_bat_cg_addr(KING_BG0SUB, 0, PAGE0_BASE >> 10);
    king_set_scroll(KING_BG0, 0, 0);
    king_set_scroll(KING_BG0SUB, 0, 0);

    /* BG0 needs the rotate microprogram: 8 ROTATE slots, then NOPs.
     * Without this the plane displays garbage or nothing at all. */
    for (i = 0; i < 8; i++)
        microprogram[i] = KING_CODE_ROTATE;
    for (; i < 16; i++)
        microprogram[i] = KING_CODE_NOP;
    king_disable_microprogram();
    king_write_microprogram(microprogram, 0, 16);
    king_enable_microprogram();

    king_set_bg_prio(KING_BGPRIO_0, KING_BGPRIO_HIDE,
                     KING_BGPRIO_HIDE, KING_BGPRIO_HIDE, 1);

    /* Affine coefficients MUST be written explicitly, or BG0 shows nothing.
     * 8.8 fixed point. A=D=0x100 is 1:1; B=C=0 no shear; X0=Y0=0 origin. */
    king_reg16(0x38, 0x0100);   /* A: source_x step per display_x */
    king_reg16(0x39, 0x0000);   /* B */
    king_reg16(0x3a, 0x0000);   /* C */
    king_reg16(0x3b, 0x0100);   /* D: source_y step per display_y */
    king_reg16(0x3c, 0x0000);   /* centre X */
    king_reg16(0x3d, 0x0000);   /* centre Y */

    tetsu_set_king_palette(0, 0, 0, 0);
    tetsu_set_video_mode(TETSU_LINES_262, 0, TETSU_DOTCLOCK_5MHz,
                         TETSU_COLORS_256, TETSU_COLORS_16,
                         0 /*vdc bg*/, 0 /*vdc spr*/,
                         1 /*bg0*/, 0, 0, 0, 0 /*rainbow*/);

    set_palette();
    contrlr_pad_init(0);

    kram_fill(PAGE0_BASE, 0x0101, PAGE_WORDS);
    kram_fill(PAGE1_BASE, 0x0101, PAGE_WORDS);
    draw_box(PAGE0_BASE, 0, 0, 256, 8, 3);
    draw_box(PAGE1_BASE, 0, 0, 256, 8, 3);

    for (;;) {
        unsigned back = front ^ 1u;
        u32 pad  = contrlr_pad_read(0);
        u32 base = back ? PAGE1_BASE : PAGE0_BASE;

        if (pad & JOY_LEFT)  bx -= 3;
        if (pad & JOY_RIGHT) bx += 3;
        if (pad & JOY_UP)    by -= 3;
        if (pad & JOY_DOWN)  by += 3;

        bx += vx;
        if (bx < 0)   { bx = 0;   vx = -vx; }
        if (bx > 224) { bx = 224; vx = -vx; }
        if (by < 0)   by = 0;
        if (by > 208) by = 208;

        /* Each page retains its old frame. Erase only that page's old square,
         * then draw the new one; the background and blue band are static. */
        if (old_bx[back] >= 0)
            draw_box(base, (unsigned)old_bx[back], (unsigned)old_by[back],
                     32, 32, 1);
        draw_box(base, (unsigned)(bx & ~1), (unsigned)by, 32, 32, 5);
        old_bx[back] = bx & ~1;
        old_by[back] = by;

        /* Flip during blanking: point both BG0 CG registers at the finished
         * page. The next iteration renders into the other page. */
        wait_frame();
        king_set_bat_cg_addr(KING_BG0, 0, base >> 10);
        king_set_bat_cg_addr(KING_BG0SUB, 0, base >> 10);
        front = back;
    }

    return 0;
}
